name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
jobs:
  build:
   runs-on: ubuntu-20.04
   steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Setup dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.202"
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: "5.6.9"
    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
    - name: Build
      run: | 
        version=${{ steps.gitversion.outputs.nuGetVersionV2 }}
        if [ "${{ github.event_name }}" == "pull_request" ] then
            version=$version-${{ steps.gitversion.outputs.shortSha }}
        fi
        dotnet build -c Release -p:Version=$version
    - name: Test
      run: dotnet test -c Release --no-build
    - name: NuGet Push
      run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
